import { PrescoutingTeamRanking } from './types';

export const PRESCOUTING_SEASON_YEAR = 2026;

export const PRESCOUTING_TEAMS: PrescoutingTeamRanking[] = [
  { rank: 1, teamNumber: 341, event1Points: 76, event2Points: 78, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 154, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 2, teamNumber: 316, event1Points: 77, event2Points: 73, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 150, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 3, teamNumber: 8513, event1Points: 73, event2Points: 68, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 141, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 4, teamNumber: 2607, event1Points: 66, event2Points: 72, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 138, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 5, teamNumber: 1403, event1Points: 73, event2Points: 62, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 135, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 6, teamNumber: 103, event1Points: 61, event2Points: 72, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 133, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 7, teamNumber: 9094, event1Points: 60, event2Points: 72, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 132, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 8, teamNumber: 1218, event1Points: 69, event2Points: 60, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 129, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 9, teamNumber: 5895, event1Points: 53, event2Points: 73, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 126, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 10, teamNumber: 2590, event1Points: 60, event2Points: 65, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 125, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 11, teamNumber: 1391, event1Points: 44, event2Points: 78, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 122, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 12, teamNumber: 5181, event1Points: 58, event2Points: 60, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 118, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 13, teamNumber: 272, event1Points: 59, event2Points: 59, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 118, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 14, teamNumber: 3637, event1Points: 58, event2Points: 57, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 115, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 15, teamNumber: 11, event1Points: 50, event2Points: 64, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 114, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 16, teamNumber: 1676, event1Points: 51, event2Points: 63, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 114, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 17, teamNumber: 484, event1Points: 40, event2Points: 66, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 106, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 18, teamNumber: 2539, event1Points: 51, event2Points: 53, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 104, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 19, teamNumber: 1923, event1Points: 30, event2Points: 72, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 102, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 20, teamNumber: 8706, event1Points: 25, event2Points: 71, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 96, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 21, teamNumber: 9015, event1Points: 30, event2Points: 61, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 91, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 22, teamNumber: 1640, event1Points: 41, event2Points: 50, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 91, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 23, teamNumber: 3314, event1Points: 36, event2Points: 54, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 90, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 24, teamNumber: 433, event1Points: 39, event2Points: 49, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 88, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 25, teamNumber: 1672, event1Points: 43, event2Points: 43, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 86, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 26, teamNumber: 56, event1Points: 51, event2Points: 34, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 85, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 27, teamNumber: 555, event1Points: 38, event2Points: 45, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 83, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 28, teamNumber: 293, event1Points: 31, event2Points: 52, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 83, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 29, teamNumber: 6921, event1Points: 23, event2Points: 58, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 81, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 30, teamNumber: 486, event1Points: 32, event2Points: 48, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 80, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 31, teamNumber: 7045, event1Points: 44, event2Points: 36, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 80, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 32, teamNumber: 222, event1Points: 42, event2Points: 36, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 78, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 33, teamNumber: 7587, event1Points: 47, event2Points: 30, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 77, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 34, teamNumber: 193, event1Points: 38, event2Points: 38, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 76, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 35, teamNumber: 708, event1Points: 40, event2Points: 36, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 76, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 36, teamNumber: 5401, event1Points: 45, event2Points: 30, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 75, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 37, teamNumber: 10949, event1Points: 43, event2Points: 21, districtChampPoints: null, rookieBonusPoints: 10, totalPoints: 74, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 38, teamNumber: 4285, event1Points: 26, event2Points: 46, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 72, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 39, teamNumber: 7110, event1Points: 38, event2Points: 33, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 71, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 40, teamNumber: 1168, event1Points: 25, event2Points: 46, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 71, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 41, teamNumber: 1089, event1Points: 31, event2Points: 38, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 69, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 42, teamNumber: 423, event1Points: 31, event2Points: 36, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 67, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 43, teamNumber: 25, event1Points: 30, event2Points: 37, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 67, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 44, teamNumber: 223, event1Points: 34, event2Points: 31, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 65, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 45, teamNumber: 10157, event1Points: 25, event2Points: 34, districtChampPoints: null, rookieBonusPoints: 5, totalPoints: 64, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 46, teamNumber: 5438, event1Points: 29, event2Points: 33, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 62, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 47, teamNumber: 5789, event1Points: 27, event2Points: 34, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 61, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 48, teamNumber: 10400, event1Points: 26, event2Points: 30, districtChampPoints: null, rookieBonusPoints: 5, totalPoints: 61, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 49, teamNumber: 427, event1Points: 28, event2Points: 32, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 60, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 50, teamNumber: 303, event1Points: 32, event2Points: 28, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 60, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 51, teamNumber: 10584, event1Points: 36, event2Points: 19, districtChampPoints: null, rookieBonusPoints: 5, totalPoints: 60, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 52, teamNumber: 10979, event1Points: 32, event2Points: 18, districtChampPoints: null, rookieBonusPoints: 10, totalPoints: 60, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 53, teamNumber: 5732, event1Points: 38, event2Points: 21, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 59, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 54, teamNumber: 1807, event1Points: 27, event2Points: 32, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 59, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 55, teamNumber: 365, event1Points: 22, event2Points: 36, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 58, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 56, teamNumber: 2016, event1Points: 20, event2Points: 37, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 57, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 57, teamNumber: 1811, event1Points: 22, event2Points: 35, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 57, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 58, teamNumber: 1712, event1Points: 20, event2Points: 37, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 57, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 59, teamNumber: 9416, event1Points: 37, event2Points: 19, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 56, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 60, teamNumber: 10070, event1Points: 18, event2Points: 33, districtChampPoints: null, rookieBonusPoints: 5, totalPoints: 56, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 61, teamNumber: 10993, event1Points: 8, event2Points: 37, districtChampPoints: null, rookieBonusPoints: 10, totalPoints: 55, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 62, teamNumber: 75, event1Points: 24, event2Points: 31, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 55, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 63, teamNumber: 4575, event1Points: 35, event2Points: 19, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 54, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 64, teamNumber: 41, event1Points: 29, event2Points: 25, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 54, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 65, teamNumber: 9027, event1Points: 28, event2Points: 26, districtChampPoints: null, rookieBonusPoints: null, totalPoints: 54, qualifiedForDcmp: false, qualifiedForCmp: false },
  { rank: 66, teamNumber: 10918, event1Points: 13, event2Points: 31, districtChampPoints: null, rookieBonusPoints: 10, totalPoints: 54, qualifiedForDcmp: false, qualifiedForCmp: false },
];

export const PRESCOUTING_TEAM_NUMBERS = PRESCOUTING_TEAMS.map((row) => row.teamNumber);
